const quotes = [
    "The greatest glory in living lies not in never falling, but in rising every time we fall. -Nelson Mandela",
    "The way to get started is to quit talking and begin doing. -Walt Disney",
    "Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma – which is living with the results of other people's thinking. -Steve Jobs",
    "The future belongs to those who believe in the beauty of their dreams. -Eleanor Roosevelt",
    "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough. -Oprah Winfrey",
    "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success. -James Cameron",
    "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one. -John Lennon",
    "You must be the change you wish to see in the world. -Mahatma Gandhi",
    "Spread love everywhere you go. Let no one ever come to you without leaving happier. -Mother Teresa",
    "The only thing we have to fear is fear itself. -Franklin D. Roosevelt",
    "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that. -Martin Luther King Jr.",
    "Do one thing every day that scares you. -Eleanor Roosevelt",
    "Well done is better than well said. -Benjamin Franklin",
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. -Helen Keller",
    "It is during our darkest moments that we must focus to see the light. -Aristotle",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. -Ralph Waldo Emerson",
    "Be yourself; everyone else is already taken. -Oscar Wilde",
    "The only limit to our realization of tomorrow is our doubts of today. -Franklin D. Roosevelt",
    "In the end, we will remember not the words of our enemies, but the silence of our friends. -Martin Luther King Jr.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. -Winston Churchill",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. -Ralph Waldo Emerson",
    "Life is what happens when you're busy making other plans. -John Lennon",
    "The purpose of our lives is to be happy. -Dalai Lama",
    "Get busy living or get busy dying. -Stephen King",
    "You only live once, but if you do it right, once is enough. -Mae West",
    "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well. -Ralph Waldo Emerson",
    "In three words I can sum up everything I've learned about life: it goes on. -Robert Frost",
    "Good friends, good books, and a sleepy conscience: this is the ideal life. -Mark Twain",
    "Life would be tragic if it weren't funny. -Stephen Hawking",
    "Everything you can imagine is real. -Pablo Picasso",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. -Buddha",
    "To love and be loved is to feel the sun from both sides. -David Viscott",
    "It is our choices that show what we truly are, far more than our abilities. -J.K. Rowling",
    "There is only one happiness in this life, to love and be loved. -George Sand",
    "Life is really simple, but we insist on making it complicated. -Confucius",
    "Love the life you live. Live the life you love. -Bob Marley",
    "In the end, it's not the years in your life that count. It's the life in your years. -Abraham Lincoln",
    "I have not failed. I've just found 10,000 ways that won't work. -Thomas Edison",
    "You have within you right now, everything you need to deal with whatever the world can throw at you. -Brian Tracy",
    "Believe you can and you're halfway there. -Theodore Roosevelt",
    "The only way to do great work is to love what you do. -Steve Jobs",
    "Do what you can, with what you have, where you are. -Theodore Roosevelt",
    "The secret of getting ahead is getting started. -Mark Twain",
    "Success is how high you bounce when you hit bottom. -George S. Patton",
    "It does not matter how slowly you go as long as you do not stop. -Confucius",
    "With the new day comes new strength and new thoughts. -Eleanor Roosevelt",
    "The journey of a thousand miles begins with one step. -Lao Tzu",
    "Don't watch the clock; do what it does. Keep going. -Sam Levenson",
    "A person who never made a mistake never tried anything new. -Albert Einstein",
    "The harder the conflict, the greater the triumph. -George Washington",
    "Don't judge each day by the harvest you reap but by the seeds that you plant. -Robert Louis Stevenson",
    "Do not wait to strike till the iron is hot; but make it hot by striking. -William Butler Yeats",
    "The way to get started is to quit talking and begin doing. -Walt Disney",
    "The best revenge is massive success. -Frank Sinatra",
    "It is never too late to be what you might have been. -George Eliot",
    "Dream big and dare to fail. -Norman Vaughan",
    "Act as if what you do makes a difference. It does. -William James",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. -Ralph Waldo Emerson",
    "Whatever you are, be a good one. -Abraham Lincoln",
    "The mind is everything. What you think you become. -Buddha",
    "You must be the change you wish to see in the world. -Mahatma Gandhi",
    "The future depends on what you do today. -Mahatma Gandhi",
    "Your time is limited, so don't waste it living someone else's life. -Steve Jobs",
    "Keep your face always toward the sunshine—and shadows will fall behind you. -Walt Whitman",
    "Turn your wounds into wisdom. -Oprah Winfrey",
    "Life is ten percent what happens to us and ninety percent how we respond to it. -Charles R. Swindoll",
    "You are never too old to set another goal or to dream a new dream. -C.S. Lewis",
    "If you can dream it, you can achieve it. -Zig Ziglar",
    "The most common way people give up their power is by thinking they don't have any. -Alice Walker",
    "Keep smiling, because life is a beautiful thing and there's so much to smile about. -Marilyn Monroe",
    "We know what we are, but know not what we may be. -William Shakespeare",
    "If you tell the truth, you don't have to remember anything. -Mark Twain",
    "Be yourself; everyone else is already taken. -Oscar Wilde",
    "The best way to predict your future is to create it. -Abraham Lincoln",
    "Imagination is everything. It is the preview of life's coming attractions. -Albert Einstein",
    "The only impossible journey is the one you never begin. -Tony Robbins",
    "When you cease to dream, you cease to live. -Malcolm Forbes",
    "Happiness is not something ready made. It comes from your own actions. -Dalai Lama",
    "You miss 100% of the shots you don't take. -Wayne Gretzky",
    "The best time to plant a tree was 20 years ago. The second best time is now. -Chinese Proverb",
    "It is never too late to be what you might have been. -George Eliot",
    "If you want to lift yourself up, lift up someone else. -Booker T. Washington",
    "Fall seven times, stand up eight. -Japanese Proverb",
    "Keep your eyes on the stars, and your feet on the ground. -Theodore Roosevelt",
    "It is our choices that show what we truly are, far more than our abilities. -J.K. Rowling",
    "Perseverance is not a long race; it's many short races one after the other. -Walter Elliot",
    "If you could kick the person in the pants responsible for most of your trouble, you wouldn't sit for a month. -Theodore Roosevelt",
    "The question isn't who is going to let me; it's who is going to stop me. -Ayn Rand",
    "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. -Mark Twain",
    "Change your thoughts and you change your world. -Norman Vincent Peale",
    "In the middle of every difficulty lies opportunity. -Albert Einstein",
    "Nothing is impossible, the word itself says 'I'm possible'! -Audrey Hepburn",
    "Everything you’ve ever wanted is on the other side of fear. -George Addair",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. -Albert Schweitzer",
    "I can't change the direction of the wind, but I can adjust my sails to always reach my destination. -Jimmy Dean",
    "Start where you are. Use what you have. Do what you can. -Arthur Ashe"
];


function QuoteGenerate() {
    document.getElementById('quote').textContent = quotes[Math.floor(Math.random() * quotes.length)];
}
Quote();
